name: quizu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  google_fonts: ^3.0.1
  hexcolor: ^2.0.7
  get_storage: ^2.0.3
  flutter_svg: ^1.1.5
  flutter_spinkit: ^5.1.0
  pin_code_fields: ^7.4.0
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^5.0.2
  phone_number: ^1.0.0
  simple_timer: ^2.0.0
  share_plus: ^4.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

